import "~/styles/globals.css";
import "@uploadthing/react/styles.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { type Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import TopNav from "./_components/TopNav";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "~/app/api/uploadthing/core";

export const metadata: Metadata = {
  title: "T3 Gallery",
  description: "T3 Gallery project by Raghav, deployed on Vercel!",
  icons: [{ rel: "icon", url: "../website-address.png" }],
};

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

// export const metadata: Metadata = {
//   title: 'Clerk Next.js Quickstart',
//   description: 'Generated by create next app',
// }

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
  modal
}: Readonly<{ children: React.ReactNode;
  modal:React.ReactNode;
 }>) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${geist.variable} flex flex-col gap-4`}>
      <body>
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)}
        />
        <TopNav />
        {children}
        {modal}
        <div id="modal-root"/>
        </body>
    </html>
    </ClerkProvider>
  );
}
